package my.vaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Panel;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AdminPanelDesign extends CssLayout {
    protected Button home;
    protected Panel ankietyPanel;
    protected Panel sklepyPanel;
    protected TextField ulica;
    protected TextField nrBudynku;
    protected TextField kod;
    protected TextField miejscowosc;
    protected Button save;
    protected Button delete;
    protected CssLayout uzytPanel;
    protected TextField imie;
    protected TextField nazwisko;
    protected TextField pesel;
    protected TextField email;
    protected Button save1;
    protected Button delete1;

    public AdminPanelDesign() {
        Design.read(this);
    }
}
